name: Zig

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2645+affe45b31
      - run: zig build test --summary all
